/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;
import java.util.Random;

public class App {

     

    public static void main(String[] args) {
        int number = 0;
        Player player = new Player();
        int guess = 0;
        Random dice = new Random();
        do {
            guess = dice.nextInt();

            number = player.guess();
        }
        while(number !=guess);
   }
}
