/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class App {

    public static void main(String[] args) {
        Player player = null;

        /*
         * try{ player = new Player("Janek"); } catch(IllegalArgumentException e){
         * System.out.println("Niepoprawne imię"); System.exit(-1); }
         */
        Result<Player> resPlayer = Player.getPlayer("Janek");
        if (!resPlayer.ok()) {
            System.out.println("Niepoprawne imię");
            System.exit(-1);
        }
        player = resPlayer.unwrap();
        Game game = new Game();
        game.addPlayer(player);
        game.play();
    }
}
